### ISSUE TITLE
Unable to connect to postgresql instance in Azure because of @ in username

### ISSUE THREAD

**Issue by andershermansen** [quay/clair#1025]
### Description of Problem / Feature Request

Unable to connect to Postgresql which runs as an Azure service because username contains @

### Expected Outcome

Able to connect to Azure Postgresql

#### Try with username@server
Config:
```
clair:
  database:
    type: pgsql
    options:
      source: "host=XXXX.postgres.database.azure.com port=5432 user=MYUSERNAME@MYSERVER password=MYPASSWORD sslmode=disable statement_timeout=60000"
```
Output:
`{"Event":"pgsql: could not open database: pq: Invalid connection parameters specified. Check connection parameters, and try again.","Level":"fatal","Location":"main.go:96","Time":"2020-08-06 12:19:47.111109"}`

#### Try with only username
Config:
```
clair:
  database:
    type: pgsql
    options:
      source: "host=XXXX.postgres.database.azure.com port=5432 user=MYUSERNAME password=MYPASSWORD sslmode=disable statement_timeout=60000"
```
Output:
`{"Event":"pgsql: could not open database: pq: Invalid Username specified. Please check the Username and retry connection. The Username should be in \u003cusername@hostname\u003e format.","Level":"fatal","Location":"main.go:96","Time":"2020-08-06 12:28:23.028421"}`

### Environment

- Clair version/image: quay.io/coreos/clair:latest (sha256:ad866ba06505c3a0710c44e7e85ed863096a4fb1ba18cbe8efbe6e9ae0c5507f)
- Clair client name/version: not applicable
- Host OS: Azure AppService WebApp for Containers
- Kernel (e.g. `uname -a`): unknown
- Kubernetes version (use `kubectl version`): n/a
- Helm version (use `helm version`): n/a
- Network/Firewall setup: n/a

**Comment by andershermansen** [comment]
I was able to work around this issue by using URL syntax for the connection instead. Because then I could use escape character %40 instead of @ as described in https://github.com/MicrosoftDocs/azure-docs/issues/6371
This escaping did not work when not using url syntax.

```
clair:
  database:
    type: pgsql
    options:
      source: "postgres://MYUSERNAME%40MYSERVER:MYPASSWORD@XXXX.postgres.database.azure.com:5432/clair?sslmode=require"
```

So I still think this is a bug (or yaml encoding issue by me) since the username with @ can not be put in the config file when not using url.
