### ISSUE TITLE
Clair 4.0.0-rc.11 - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by smitphilip** [quay/clair#1084]
### Description of Problem / Feature Request

Running version 4.0.0-rc.11 of clair results in a panic runtime error. 

### Expected Outcome

Expecting container to successfully initialise

### Actual Outcome
```
1:28PM INF logging initialized component=init/Init.Logging
1:28PM INF begin service initialization component=init/Init.Services
1:28PM INF created database connection component=libindex/New
1:28PM DBG initializing local updater job. this log should only be seen once. component=rhel/RepositoryScanner/NewRepositoryScanner version=1.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xc06daa]
goroutine 1 [running]:
github.com/quay/claircore/rhel/repo2cpe.(*LocalUpdaterJob).do(0xc0002fe240, 0xfa6100, 0xc00003a040, 0x0, 0x0)
	/go/pkg/mod/github.com/quay/claircore@v0.1.10/rhel/repo2cpe/updater.go:128 +0x3ea
github.com/quay/claircore/rhel/repo2cpe.(*LocalUpdaterJob).Start(0xc0002fe240, 0xfa6100, 0xc00003a040, 0x0, 0x1f4)
	/go/pkg/mod/github.com/quay/claircore@v0.1.10/rhel/repo2cpe/updater.go:82 +0x3a5
github.com/quay/claircore/rhel.NewRepositoryScanner.func1()
	/go/pkg/mod/github.com/quay/claircore@v0.1.10/rhel/repositoryscanner.go:89 +0xe5
sync.(*Once).doSlow(0x14bfa40, 0xc00028df58)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
github.com/quay/claircore/rhel.NewRepositoryScanner(0xfa6180, 0xc0002f25a0, 0x0, 0xea76c9, 0x43, 0xc00028e401)
	/go/pkg/mod/github.com/quay/claircore@v0.1.10/rhel/repositoryscanner.go:77 +0x435
github.com/quay/claircore/rhel.NewEcosystem.func3(0xfa6180, 0xc0002f25a0, 0x14f3678, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/quay/claircore@v0.1.10/rhel/ecosystem.go:24 +0x4a
github.com/quay/claircore/internal/indexer.EcosystemsToScanners(0xfa6180, 0xc0002f25a0, 0xc000295890, 0x5, 0x5, 0xc0001cbf00, 0x0, 0x0, 0xc000296a40, 0x2, ...)
	/go/pkg/mod/github.com/quay/claircore@v0.1.10/internal/indexer/ecosystem.go:73 +0x6e4
github.com/quay/claircore/libindex.New(0xfa6180, 0xc000295770, 0xc00018c510, 0xc0001fd0e0, 0x0, 0xc0001af200)
	/go/pkg/mod/github.com/quay/claircore@v0.1.10/libindex/libindex.go:64 +0x5f2
github.com/quay/clair/v4/initialize.(*Init).Services(0xc0002bea00, 0x0, 0x0)
	/build/initialize/services.go:65 +0x6d6
github.com/quay/clair/v4/initialize.New(0xe77633, 0x5, 0xc00029b030, 0xc, 0xc00029b010, 0xc, 0xc00029b060, 0xb, 0xc00003c8d0, 0x2d, ...)
	/build/initialize/init.go:52 +0xc5
main.main()
	/build/cmd/clair/main.go:55 +0x5e5
```

### Environment

Clair Deployment yaml:
```
    spec:
      containers:
        - name: clair
          image: quay.io/coreos/clair:v4.0.0-rc.11
          imagePullPolicy: IfNotPresent
          env:
            - name: HOME
              value: /tmp
            - name: CLAIR_CONF
              value: /clair/config.yaml
            - name: CLAIR_MODE
              value: combo
          ports:
            - containerPort: 8080
              name: clair-http
              protocol: TCP
          volumeMounts:
            - mountPath: /clair/
              name: config
```

Clair Config File:
```
introspection_addr: 0.0.0.0:8089
http_listen_addr: 0.0.0.0:8080
log_level: debug-color
indexer:
  connstring: 'postgresql://postgres:postgres@postgres/clair'
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: false
  scanner: {}
matcher:
  indexer_addr: "127.0.0.1:8080"
  connstring: 'postgresql://postgres:postgres@postgres/clair'
  max_conn_pool: 100
  run: ""
  migrations: false
  updater_sets:
  - "alpine"
notifier:
  connstring: 'postgresql://postgres:postgres@postgres/clair'
  migrations: false
  indexer_addr: "127.0.0.1:8080"
  matcher_addr: "127.0.0.1:8080"
  poll_interval: "60s"
  delivery_interval: "500s"
  webhook: null
  amqp: null
  stomp: null
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent_endpoint: "localhost:6831"
    service_name: "clair"
metrics:
  name: "prometheus"
```

- **Clair version/image:** 
quay.io/coreos/clair:v4.0.0-rc.11
- **Clair client name/version:** 
N/A
- **Host OS:** 
Red Hat Enterprise Linux Server release 7.8 (Maipo)
- **Kernel** (e.g. `uname -a`): 
Linux (hostname) 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Kubernetes version (use `kubectl version`):** 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- **Network/Firewall setup:** 
N/A
