### ISSUE TITLE
Is TLS authentication not supported for openapi ?

### ISSUE THREAD

**Issue by bluefriday** [quay/clair#1430]
### Description of Problem / Feature Request

According to the Clair documents(https://quay.github.io/clair/concepts/authentication.html)
It is said to support 'quay integrated authentication' and 'PSK authentication'.
Is TLS authentication not supported for openapi ?

```
auth:
  psk:
    key: >-
      MDQ4ODBlNDAtNDc0ZC00MWUxLThhMzAtOTk0MzEwMGQwYTMxCg==
    iss: 'issuer'
```
