### ISSUE TITLE
Clair Indexing timeout in offline mode

### ISSUE THREAD

**Issue by bluefriday** [quay/clair#1433]
I ran Clair in an offline environment.

After that, when I request the index_report API(/indexer/api/v1/index_report), the indexer sends a request to the online environment. 

And after waiting 30 seconds (probably a timeout) the indexing operation happens.

How can I change the configuration of the indexer to offline mode so that the timeout does not occur? (I tried using the airgap flag, but it didn't work.)

my configuration of indexer clair :
```
  config.yaml: |
    introspection_addr: :8089
    http_listen_addr: :6060
    log_level: debug-color
    indexer:
      connstring: host=svc-indexer-db port=5432 dbname=clair user=postgres password=postgres sslmode=disable
      scanlock_retry: 10
      layer_scan_concurrency: 5
      migrations: true
      airgap: true
```
- Clair version/image: v4.3.2
- Clair client name/version: 0.2.0
- Host OS: centos7.4
- Kernel (e.g. `uname -a`): 3.10.0-957.el7.x86_64
- Kubernetes version (use `kubectl version`): 1.22.0
- Network/Firewall setup: X

**Comment by hdonnay** [comment]
Please provide information (if you have it) about what request was made.

This smells like it could be the rhel package scanner, but it's hard to say without any logging.

**Comment by bluefriday** [comment]
> Please provide information (if you have it) about what request was made.
> 
> This smells like it could be the rhel package scanner, but it's hard to say without any logging.

Ok, I reproduced my test :)


indexer's log 
```
4:41AM INF index request start component=libindex/Libindex.Index manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
4:41AM DBG configured search API URL api=https://search.maven.org/solrsearch/select component=java/Scanner.Configure manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108 version=3
4:41AM DBG attempting fetch of repo2cpe mapping file component=rhel/repo2cpe/UpdatingMapper.do manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108 url=https://access.redhat.com/security/data/metrics/repository-to-cpe.json version=1.1


4:41AM ERR configuration failed error="Get \"https://access.redhat.com/security/data/metrics/repository-to-cpe.json\": dial tcp 23.25.172.12:443: i/o timeout" component=internal/indexer/layerscannner/New manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108 scanner=rhel-repository-scanner
4:41AM DBG locking attempt component=libindex/Libindex.Index manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
4:41AM DBG locking OK component=libindex/Libindex.Index manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
4:41AM INF starting scan component=internal/indexer/controller/Controller.Index manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
```

indexer clair's configuration
```
apiVersion: v1
kind: ConfigMap
...
data:
  config.yaml: |
    introspection_addr: :8089
    http_listen_addr: :6060
    log_level: debug-color
    indexer:
      connstring: host=svc-indexer-db port=5432 dbname=clair user=postgres password=postgres sslmode=disable
      scanlock_retry: 10
      layer_scan_concurrency: 5
      migrations: true
      airgap: true
      scanner: {}
```
