### ISSUE TITLE
"docker" deploy support of postgres 9.3.12 

### ISSUE THREAD

**Issue by westlifezs** [quay/clair#191]
It looks like clair now only supports postgres 9.4+, right?
A couple of weeks ago I was able to use postgres 9.3.12 to server clair and see the db can be connected successfully. However, when I upgraded to the latest version of clair image with the same config file. I see an error in the container log saying:

2016-05-26 18:44:13.033496 C | main: pgsql: no database connection string specified

Is this because of the version conflict issue? or something wrong with my configuration.

in "/root/clair_config/config.yaml" I have postgres connection configured as following:

```
source: postgresql://postgres:password@postgres:5432?sslmode=disable
```

Also postgres server is running in my local host.

Any thoughts?

**Comment by jgsqware** [comment]
Could you check your configuration, since 1.2.2 the config has changed:
Have a look to the type and options tag:

``` yaml
clair:
  database:
    # Database driver
    type: pgsql
    options:
      # PostgreSQL Connection string
      # http://www.postgresql.org/docs/9.4/static/libpq-connect.html
      source: postgresql://postgres:root@postgres:5432?sslmode=disable

      # Number of elements kept in the cache
      # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
      cachesize: 16384
```
