### ISSUE TITLE
main: failed to load configuration: yaml: line 23: did not find expected key

### ISSUE THREAD

**Issue by hlysecpro** [quay/clair#230]
Hi all,

when I run the container with :
docker run -d  -v $HOME/clair_config:/config quay.io/coreos/clair:v1.2.2 -config=/config/config.yaml

It failed with saying that:
2016-08-13 06:16:16.987993 C | main: failed to load configuration: yaml: line 23: did not find expected key

Any advice and suggestions will be greatly appreciated. The config.yaml is as follow:

![image](https://cloud.githubusercontent.com/assets/21004507/17642013/75da9af8-6169-11e6-9ad3-028de664da27.png)

**Comment by Quentin-M** [comment]
Hi,

You may compare it to: https://github.com/coreos/clair/blob/master/config.example.yaml

```
clair:
  database:
    # Database driver
    type: pgsql
    options:
      # PostgreSQL Connection string
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      source:

      # Number of elements kept in the cache
      # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
      cachesize: 16384
[...]
```
