### ISSUE TITLE
vulnsrc/alpine: yaml parsing error skip all parsable ones

### ISSUE THREAD

**Issue by tedli** [quay/clair#337]
[shadow](http://git.alpinelinux.org/cgit/alpine-secdb/commit/?id=593c1a565bb75726b284d2b7afc563e7ffdc86f5) commit on 2017/03/01 causes yaml parsing error.
This `*yaml.TypeError` was returned to the top level `Updater` making other parsable ones not be inserted into the database.
If an error is parsing error, since it lose more returning the error to the caller, it may be better logging it than break an update iteration.

**Comment by tedli** [comment]
```yaml
- pkg:
  name: shadow
    secfixes:
      ** here should be a version, but nothing here **
      - CVE-2016-6252
      - CVE-2017-2616
- pkg:
  name: slock
    secfixes:
      1.3-r3:
```
