### ISSUE TITLE
Alpine updater fails [unmarshal errors]

### ISSUE THREAD

**Issue by arminc** [quay/clair#409]
Since 3 of June the Alpine updater fails when parsing the incoming data with CVE. See the error below: 

```
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:220","Time":"2017-06-04 20:01:22.077012","error":"yaml: unmarshal errors:\n  line 33: cannot unmarshal !!str `CVE-201...` into []string","updater name":"alpine"}
```

Do others have the same problem? Is this something clair needs to fix or is this is a mistake on the other side?

**Comment by jzelinskie** [comment]
My intuition is that this is an upstream error.
Somewhere there's YAML that looks like this:

```yaml
  - pkg:
      name: gtk-vnc
      secfixes:
        0.7.0-r0: CVE-2017-5884
```

when it should look like this:


```yaml
  - pkg:
      name: gtk-vnc
      secfixes:
        0.7.0-r0:
        - CVE-2017-5884
```

I'll try and track it down when I have some time free.
