### ISSUE TITLE
how to run clair when installing from source code

### ISSUE THREAD

**Issue by fireburn13** [quay/clair#664]
### Description of Problem / Feature Request
I deployed clair on my centos host yesterday by following this guide:
Source

To build Clair, you need to latest stable version of Go and a working Go environment. In addition, Clair requires some additional binaries be installed on the system $PATH as runtime dependencies:

git
rpm
xz
$ go get github.com/coreos/clair
$ go install github.com/coreos/clair/cmd/clair
$ $EDITOR config.yaml # Add the URI for your postgres database
$ ./$GOPATH/bin/clair -config=config.yaml

I am able to kick off the installation yesterday and I saw the database connection was successful. This morning I came in and ran this command to validate the installation of clair.

 curl -X GET -I http://127.0.0.1:6060/health and I got this:

curl: (7) Failed connect to 127.0.0.1:6060; Connection refused

I was able to get clair up and running using docker but since we need to modify the CVE datasource from internet to a local repository we will need to use the source code compile method.

Did I do anything wrong here? how to get the clair up and running when installing from source code?

### Expected Outcome

HTTP/1.1 200 OK
Server: clair
Date: Wed, 04 May 2016 20:02:16 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

### Actual Outcome
curl: (7) Failed connect to 127.0.0.1:6060; Connection refused

### Environment

- Clair version/image: 2.0.6 stable
- Clair client name/version: clair 2.0.6 stable
- Host OS: centos 
- Kernel (e.g. `uname -a`): 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes version (use `kubectl version`):  N/A
- Helm version (use `helm version`):  N/A
- Network/Firewall setup:  local host, firewall disabled

**Comment by KeyboardNerd** [comment]
It's hard to know, is there anything bound to port 6060? Clair may not running on that port at all.

**Comment by fireburn13** [comment]
well, here is the config.yaml file, yes , it should use 6060 for health check.

```yaml
# The values specified here are the default values that Clair uses if no configuration file is specified or if the keys are not defined.
clair:
  database:
    # Database driver
    type: pgsql
    options:
      # PostgreSQL Connection string
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      source: host=#########.amazonaws.com port=#### database=c#### user=#### sslmode=disable statement_timeout=60000 password=#####

      # Number of elements kept in the cache
      # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
      cachesize: 16384

      # 32-bit URL-safe base64 key used to encrypt pagination tokens
      # If one is not provided, it will be generated.
      # Multiple clair instances in the same cluster need the same value.
      paginationkey:

  api:
    # v3 grpc/RESTful API server address
    addr: "0.0.0.0:6060"

    # Health server address
    # This is an unencrypted endpoint useful for load balancers to check to healthiness of the clair server.
    healthaddr: "0.0.0.0:6061"

    # Deadline before an API request will respond with a 503
    timeout: 900s

    # Optional PKI configuration
    # If you want to easily generate client certificates and CAs, try the following projects:
    # https://github.com/coreos/etcd-ca
    # https://github.com/cloudflare/cfssl
    servername:
    cafile:
    keyfile:
    certfile:

  updater:
    # Frequency the database will be updated with vulnerabilities from the default data sources
    # The value 0 disables the updater entirely.
    interval: 2h
    enabledupdaters:
      - debian
      - ubuntu
      - rhel
      - oracle
      - alpine

  notifier:
    # Number of attempts before the notification is marked as failed to be sent
    attempts: 3

    # Duration before a failed notification is retried
    renotifyinterval: 2h

    http:
      # Optional endpoint that will receive notifications via POST requests
      endpoint:

      # Optional PKI configuration
      # If you want to easily generate client certificates and CAs, try the following projects:
      # https://github.com/cloudflare/cfssl
      # https://github.com/coreos/etcd-ca
      servername:
      cafile:
      keyfile:
      certfile:

      # Optional HTTP Proxy: must be a valid URL (including the scheme).
      proxy:

```
