### ISSUE TITLE
could not decode NVD data feed

### ISSUE THREAD

**Issue by Hokwang** [quay/clair#803]
I installed clair latest version using harbor latest version.

very first log show below error
```
{"Event":"adding metadata to vulnerabilities","Level":"info","Location":"updater.go:279","Time":"2019-06-19 10:05:54.060791"}
{"Event":"could not decode NVD data feed","Level":"error","Location":"nvd.go:93","Time":"2019-06-19 10:09:38.057391","data feed name":"2005","error":"unexpected EOF"}
{"Event":"an error occured when loading metadata fetcher","Level":"error","Location":"updater.go:300","Time":"2019-06-19 10:09:38.057452","appender name":"NVD","error":"updater/fetchers: could not parse"}
{"Event":"inserting vulnerabilities for update","Level":"debug","Location":"updater.go:198","Time":"2019-06-19 10:09:38.057481","count":162161}
```

Maybe I have firewall problem because I am in behind the corporate proxy, But I applied firewall exception with nvd.nist.gov
So I think this is just parsing problem.

Thanks.

### Environment
- Clair version/image: 2.0.8
- Clair client name/version: N/A
- Host OS: N/A
- Kernel (e.g. `uname -a`): N/A
- Kubernetes version (use `kubectl version`): N/A
- Helm version (use `helm version`): N/A
- Network/Firewall setup: N/A

**Comment by Hokwang** [comment]
@KeyboardNerd 
Hi, can you figure this issue out?

**Comment by hansh4** [comment]
How is this issue coming along?

**Comment by iainlbc** [comment]
I am having similar issues, also going out of a proxy but able to curl the endpoints. Setting ENV vars on the container worked for accessing the other updaters over proxy (rhel/oracle/debian/etc.).

It's also weird that its stating a XML syntax error, but should be accessing JSON endpoints right? Ref: https://github.com/coreos/clair/blob/0c2e5e73c274dfa292102b76538f5e461ebdae33/ext/vulnmdsrc/nvd/nvd.go#L41-L48

Logs:
```
{"Event":"adding metadata to vulnerabilities","Level":"info","Location":"updater.go:279","Time":"2019-06-21 14:47:31.449981"}
{"Event":"could not decode NVD data feed","Level":"error","Location":"nvd.go:93","Time":"2019-06-21 14:47:36.336927","data feed name":"2008","error":"XML syntax error on line 145125: unexpected EOF"}
{"Event":"an error occured when loading metadata fetcher","Level":"error","Location":"updater.go:300","Time":"2019-06-21 14:47:36.336989","appender name":"NVD","error":"updater/fetchers: could not parse"}
```

**Comment by ldelossa** [comment]
@Hokwang 

Can you share your clair V2.0.8 config with me ?

**Comment by Hokwang** [comment]
@ldelossa 
Hi,

here's output.
```
# cat config.yaml 
clair:
  database:
    type: pgsql
    options:
      source: "postgres://postgres:bmw_m5@harbor-prod-harbor-database:5432/postgres?sslmode=disable"
      # Number of elements kept in the cache
      # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
      cachesize: 16384

  api:
    # API server port
    port: 6060
    healthport: 6061

    # Deadline before an API request will respond with a 503
    timeout: 300s
  updater:
    interval: 12h

  notifier:
    attempts: 3
    renotifyinterval: 2h
    http:
      endpoint: "http://harbor-prod-harbor-core/service/notifications/clair"
```
